import type { Salon, Testimonial } from "@/types";

export const DEMO_SALONS: Salon[] = [
  {
    id: "1",
    slug: "luxe-spa-sukhumvit",
    status: "published",
    price_usd: 78000,
    price_thb: 2730000,
    price_eur: 71760,
    monthly_revenue_usd: 10500,
    rooms_count: 8,
    surface_sqm: 120,
    district: "Sukhumvit",
    address: "Sukhumvit Soi 24, Bangkok",
    latitude: 13.7225,
    longitude: 100.5688,
    title_fr: "Luxe Spa & Massage — Sukhumvit",
    title_en: "Luxe Spa & Massage — Sukhumvit",
    title_ru: "Люкс Спа и Массаж — Сукхумвит",
    description_fr:
      "Fonds de commerce de 120 m² au cœur de Sukhumvit Soi 24, à proximité du BTS Phrom Phong. 6 salles de massage privatisées, 1 réception, 1 espace détente. Bail commercial 3 ans restants avec option de renouvellement. Chiffre d'affaires stable (~10 500 $/mois), équipement complet inclus, équipe de 8 thérapeutes certifiés transférable. Licence spa en règle. Idéal pour investisseur recherchant une rentabilité immédiate.",
    description_en:
      "120 sqm turnkey business in the heart of Sukhumvit Soi 24, near BTS Phrom Phong. 6 private massage rooms, 1 reception, 1 lounge area. 3-year commercial lease remaining with renewal option. Stable monthly revenue (~$10,500), full equipment included, team of 8 certified therapists transferable. Spa license in order. Ideal for an investor seeking immediate yield.",
    description_ru:
      "Готовый бизнес 120 м² в самом сердце Сукхумвит Сой 24, рядом с BTS Phrom Phong. 6 приватных массажных кабинетов, ресепшн, зона отдыха. Коммерческая аренда 3 года с опцией продления. Стабильная месячная выручка (~10 500 $), оборудование и команда из 8 сертифицированных специалистов передаются новому владельцу.",
    categories: ["spa", "massage"],
    amenities: ["aircon", "wifi", "equipment_included", "staff_included", "private_rooms", "reception"],
    contact_whatsapp: "+33626741314",
    contact_line: "siamluxe",
    contact_email: "contact@siamluxe.com",
    video_url: null,
    featured: true,
    created_by: "admin",
    created_at: "2026-03-15T10:00:00Z",
    updated_at: "2026-03-15T10:00:00Z",
    photos: [
      { id: "p1", salon_id: "1", storage_path: "", url: "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=800&q=80&auto=format&fit=crop", position: 0, created_at: "" },
      { id: "p2", salon_id: "1", storage_path: "", url: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&q=80&auto=format&fit=crop", position: 1, created_at: "" },
      { id: "p3", salon_id: "1", storage_path: "", url: "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=800&q=80&auto=format&fit=crop", position: 2, created_at: "" },
      { id: "p4", salon_id: "1", storage_path: "", url: "https://images.unsplash.com/photo-1596178060671-7a80dc8059ea?w=800&q=80&auto=format&fit=crop", position: 3, created_at: "" },
    ],
  },
  {
    id: "2",
    slug: "nail-art-studio-thonglor",
    status: "published",
    price_usd: 42000,
    price_thb: 1470000,
    price_eur: 38640,
    monthly_revenue_usd: 6000,
    rooms_count: 8,
    surface_sqm: 65,
    district: "Thonglor",
    address: "Thonglor Soi 13, Bangkok",
    latitude: 13.73,
    longitude: 100.585,
    title_fr: "Nail Art Studio Premium — Thonglor",
    title_en: "Premium Nail Art Studio — Thonglor",
    title_ru: "Премиум Студия Маникюра — Тонглор",
    description_fr:
      "Studio de 65 m² sur Thonglor Soi 13, quartier à fort pouvoir d'achat. 8 postes manucure/pédicure, zone nail art, espace client. Équipement complet inclus (UV, matériel gel, stock vernis haut de gamme). Chiffre d'affaires récurrent d'environ 6 000 $/mois. Emplacement premium avec trafic piéton élevé. Fiche Google 4,7★ et forte présence Instagram — actifs digitaux inclus dans la cession.",
    description_en:
      "65 sqm studio on Thonglor Soi 13, in Bangkok's high-spending district. 8 manicure/pedicure stations, nail art zone, client lounge. Full equipment included (UV lamps, gel supplies, premium polish stock). Recurring monthly revenue around $6,000. Premium location with strong foot traffic. Google rating 4.7★ and established Instagram — digital assets included in the sale.",
    description_ru:
      "Студия 65 м² на Тонглор Сой 13, в районе с высоким уровнем доходов. 8 мест для маникюра/педикюра, зона нейл-арта, зона ожидания клиентов. Полное оборудование включено. Стабильная месячная выручка около 6 000 $. Премиальное расположение с высоким пешеходным трафиком. Google-рейтинг 4,7★, активный Instagram — цифровые активы передаются.",
    categories: ["nails"],
    amenities: ["aircon", "wifi", "equipment_included", "staff_included"],
    contact_whatsapp: "+33626741314",
    contact_line: "siamluxe",
    contact_email: "contact@siamluxe.com",
    video_url: null,
    featured: true,
    created_by: "admin",
    created_at: "2026-03-20T10:00:00Z",
    updated_at: "2026-03-20T10:00:00Z",
    photos: [
      { id: "p5", salon_id: "2", storage_path: "", url: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800&q=80&auto=format&fit=crop", position: 0, created_at: "" },
      { id: "p6", salon_id: "2", storage_path: "", url: "https://images.unsplash.com/photo-1632345031435-8727f6897d53?w=800&q=80&auto=format&fit=crop", position: 1, created_at: "" },
      { id: "p7", salon_id: "2", storage_path: "", url: "https://images.unsplash.com/photo-1610992015732-2449b76344bc?w=800&q=80&auto=format&fit=crop", position: 2, created_at: "" },
      { id: "p8", salon_id: "2", storage_path: "", url: "https://images.unsplash.com/photo-1607779097040-26e80aa78e66?w=800&q=80&auto=format&fit=crop", position: 3, created_at: "" },
    ],
  },
  {
    id: "3",
    slug: "thai-massage-center-silom",
    status: "published",
    price_usd: 98000,
    price_thb: 3430000,
    price_eur: 90160,
    monthly_revenue_usd: 14000,
    rooms_count: 10,
    surface_sqm: 180,
    district: "Silom",
    address: "Silom Soi 6, Bangkok",
    latitude: 13.726,
    longitude: 100.534,
    title_fr: "Centre de Massage Thaï — Silom",
    title_en: "Thai Massage Center — Silom",
    title_ru: "Центр Тайского Массажа — Силом",
    description_fr:
      "Centre établi de 180 m² sur Silom Soi 6, emplacement stratégique entre BTS Sala Daeng et MRT Silom. 10 espaces de massage (4 privatifs), salle traditionnelle thaïe, zone herbes et aromathérapie. Équipe de 12 masseurs diplômés Wat Pho. Chiffre d'affaires d'environ 14 000 $/mois, clientèle mixte affaires/touristes. Bail 5 ans renouvelable, licence massage traditionnelle en règle.",
    description_en:
      "Established 180 sqm center on Silom Soi 6, strategic location between BTS Sala Daeng and MRT Silom. 10 massage areas (4 private), traditional Thai hall, herbal and aromatherapy zone. Team of 12 Wat Pho certified therapists. Monthly revenue around $14,000, mixed business/tourist clientele. 5-year renewable lease, traditional massage license in order.",
    description_ru:
      "Действующий центр 180 м² на Силом Сой 6, стратегическое расположение между BTS Sala Daeng и MRT Silom. 10 массажных зон (4 приватных), традиционный тайский зал, зона ароматерапии. Команда из 12 сертифицированных Wat Pho специалистов. Месячная выручка около 14 000 $, смешанная клиентура из бизнеса и туристов.",
    categories: ["massage"],
    amenities: ["aircon", "wifi", "equipment_included", "staff_included", "private_rooms", "shower", "reception", "storage"],
    contact_whatsapp: "+33626741314",
    contact_line: "siamluxe",
    contact_email: "contact@siamluxe.com",
    video_url: null,
    featured: true,
    created_by: "admin",
    created_at: "2026-04-01T10:00:00Z",
    updated_at: "2026-04-01T10:00:00Z",
    photos: [
      { id: "p9", salon_id: "3", storage_path: "", url: "https://images.unsplash.com/photo-1596178060671-7a80dc8059ea?w=800&q=80&auto=format&fit=crop", position: 0, created_at: "" },
      { id: "p10", salon_id: "3", storage_path: "", url: "https://images.unsplash.com/photo-1559599101-f09722fb4948?w=800&q=80&auto=format&fit=crop", position: 1, created_at: "" },
      { id: "p11", salon_id: "3", storage_path: "", url: "https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=800&q=80&auto=format&fit=crop", position: 2, created_at: "" },
      { id: "p12", salon_id: "3", storage_path: "", url: "https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800&q=80&auto=format&fit=crop", position: 3, created_at: "" },
    ],
  },
  {
    id: "4",
    slug: "beauty-lounge-asoke",
    status: "published",
    price_usd: 117000,
    price_thb: 4095000,
    price_eur: 107640,
    monthly_revenue_usd: 18000,
    rooms_count: 18,
    surface_sqm: 200,
    district: "Asoke",
    address: "Asoke Montri Road, Bangkok",
    latitude: 13.738,
    longitude: 100.561,
    title_fr: "Beauty Lounge Multi-services — Asoke",
    title_en: "Multi-service Beauty Lounge — Asoke",
    title_ru: "Мультисервисный Бьюти Лаунж — Асоке",
    description_fr:
      "Ensemble de 200 m² au cœur d'Asoke combinant coiffure, soins visage, massage et ongles. 15 postes de travail, 3 cabines privatives, espace VIP. Design contemporain, équipement dernier cri. Chiffre d'affaires d'environ 18 000 $/mois, clientèle internationale fidélisée. Bail 5 ans, équipe complète transférable. Excellent retour sur investissement (ROI estimé >18 %/an).",
    description_en:
      "200 sqm complex in the heart of Asoke combining hair, facial care, massage and nails. 15 workstations, 3 private cabins, VIP area. Contemporary design, state-of-the-art equipment. Monthly revenue around $18,000, loyal international clientele. 5-year lease, full staff transferable. Excellent ROI (estimated >18%/yr).",
    description_ru:
      "Комплекс 200 м² в самом сердце Асоке, объединяющий парикмахерскую, уход за лицом, массаж и маникюр. 15 рабочих мест, 3 приватные кабины, VIP-зона. Современный дизайн, новейшее оборудование. Месячная выручка около 18 000 $, лояльная международная клиентура. Аренда на 5 лет, вся команда передаётся.",
    categories: ["multi", "hair", "nails", "massage"],
    amenities: ["aircon", "wifi", "parking", "equipment_included", "staff_included", "private_rooms", "shower", "reception", "storage"],
    contact_whatsapp: "+33626741314",
    contact_line: "siamluxe",
    contact_email: "contact@siamluxe.com",
    video_url: null,
    featured: true,
    created_by: "admin",
    created_at: "2026-04-10T10:00:00Z",
    updated_at: "2026-04-10T10:00:00Z",
    photos: [
      { id: "p13", salon_id: "4", storage_path: "", url: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&q=80&auto=format&fit=crop", position: 0, created_at: "" },
      { id: "p14", salon_id: "4", storage_path: "", url: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80&auto=format&fit=crop", position: 1, created_at: "" },
      { id: "p15", salon_id: "4", storage_path: "", url: "https://images.unsplash.com/photo-1633681926022-84c23e8cb2d6?w=800&q=80&auto=format&fit=crop", position: 2, created_at: "" },
      { id: "p16", salon_id: "4", storage_path: "", url: "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=800&q=80&auto=format&fit=crop", position: 3, created_at: "" },
    ],
  },
  {
    id: "5",
    slug: "zen-wellness-ekkamai",
    status: "published",
    price_usd: 53000,
    price_thb: 1855000,
    price_eur: 48760,
    monthly_revenue_usd: 7500,
    rooms_count: 6,
    surface_sqm: 95,
    district: "Ekkamai",
    address: "Ekkamai Soi 10, Bangkok",
    latitude: 13.722,
    longitude: 100.587,
    title_fr: "Zen Wellness & Sauna — Ekkamai",
    title_en: "Zen Wellness & Sauna — Ekkamai",
    title_ru: "Зен Велнес и Сауна — Экамай",
    description_fr:
      "Concept wellness différenciant de 95 m² à Ekkamai : sauna traditionnel, hammam, massages thaï aux herbes. 4 cabines de soins, 1 sauna, 1 hammam. Ambiance zen avec jardin intérieur. Chiffre d'affaires d'environ 7 500 $/mois, note Google 4,8★. Emplacement rare dans un quartier en pleine gentrification — opportunité pour un entrepreneur recherchant un concept déjà positionné.",
    description_en:
      "Differentiated 95 sqm wellness concept in Ekkamai: traditional sauna, hammam, Thai herbal massages. 4 treatment rooms, 1 sauna, 1 hammam. Zen atmosphere with indoor garden. Monthly revenue around $7,500, Google rating 4.8★. Rare location in a rapidly gentrifying district — opportunity for an entrepreneur seeking a pre-positioned concept.",
    description_ru:
      "Уникальная велнес-концепция 95 м² в Экамае: традиционная сауна, хаммам, тайские травяные массажи. 4 процедурных кабинета, 1 сауна, 1 хаммам. Атмосфера дзен с внутренним садом. Месячная выручка около 7 500 $, Google-рейтинг 4,8★. Редкое расположение в быстро развивающемся районе.",
    categories: ["sauna", "spa", "massage"],
    amenities: ["aircon", "wifi", "equipment_included", "private_rooms", "shower"],
    contact_whatsapp: "+33626741314",
    contact_line: "siamluxe",
    contact_email: "contact@siamluxe.com",
    video_url: null,
    featured: false,
    created_by: "admin",
    created_at: "2026-04-05T10:00:00Z",
    updated_at: "2026-04-05T10:00:00Z",
    photos: [
      { id: "p17", salon_id: "5", storage_path: "", url: "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=800&q=80&auto=format&fit=crop", position: 0, created_at: "" },
      { id: "p18", salon_id: "5", storage_path: "", url: "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=800&q=80&auto=format&fit=crop", position: 1, created_at: "" },
      { id: "p19", salon_id: "5", storage_path: "", url: "https://images.unsplash.com/photo-1583416750470-965b2707b355?w=800&q=80&auto=format&fit=crop", position: 2, created_at: "" },
      { id: "p20", salon_id: "5", storage_path: "", url: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&q=80&auto=format&fit=crop", position: 3, created_at: "" },
    ],
  },
  {
    id: "6",
    slug: "siam-beauty-521-street",
    status: "published",
    price_usd: 50000,
    price_thb: 1750000,
    price_eur: 46000,
    monthly_revenue_usd: 7000,
    rooms_count: 8,
    surface_sqm: 100,
    district: "Sukhumvit",
    address: "521 Street, Bangkok",
    latitude: 13.7437,
    longitude: 100.5483,
    title_fr: "Siam Beauty — 521 Street",
    title_en: "Siam Beauty — 521 Street",
    title_ru: "Siam Beauty — 521 Street",
    description_fr:
      "Fonds de commerce de 100 m² sur 521 Street, Bangkok. 8 pièces dédiées : manucure, pédicure, spa, soins sourcils, soins peau, soins capillaires, cabine privée VIP, accueil. Décoration contemporaine toile de Jouy récemment rénovée. Chiffre d'affaires d'environ 7 000 $/mois. Équipement haut de gamme (fauteuils massants, lustres cristal). Mobilier à définir selon accord. Idéal pour un premier investissement en Thaïlande.",
    description_en:
      "100 sqm turnkey business on 521 Street, Bangkok. 8 dedicated spaces: manicure, pedicure, spa, eyebrows, skin care, hair care, private VIP cabin, reception. Contemporary toile de Jouy decor recently renovated. Monthly revenue around $7,000. Premium equipment (massage chairs, crystal chandeliers). Furniture inclusion negotiable. Ideal first investment in Thailand.",
    description_ru:
      "Готовый бизнес 100 м² на 521 Street, Бангкок. 8 выделенных зон: маникюр, педикюр, спа, брови, уход за кожей, уход за волосами, приватная VIP-кабина, ресепшн. Современный декор toile de Jouy, недавняя реновация. Месячная выручка около 7 000 $. Премиальное оборудование. Мебель обсуждается.",
    categories: ["nails", "spa", "hair", "multi"],
    amenities: ["aircon", "wifi", "equipment_included", "private_rooms", "reception"],
    contact_whatsapp: "+33626741314",
    contact_line: "siamluxe",
    contact_email: "contact@siamluxe.com",
    video_url: null,
    featured: true,
    created_by: "admin",
    created_at: "2026-04-15T10:00:00Z",
    updated_at: "2026-04-15T10:00:00Z",
    photos: [
      { id: "p21", salon_id: "6", storage_path: "", url: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&q=80&auto=format&fit=crop", position: 0, created_at: "" },
      { id: "p22", salon_id: "6", storage_path: "", url: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800&q=80&auto=format&fit=crop", position: 1, created_at: "" },
      { id: "p23", salon_id: "6", storage_path: "", url: "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=800&q=80&auto=format&fit=crop", position: 2, created_at: "" },
      { id: "p24", salon_id: "6", storage_path: "", url: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80&auto=format&fit=crop", position: 3, created_at: "" },
    ],
  },
];

export const DEMO_TESTIMONIALS: Testimonial[] = [
  {
    id: "t1",
    author_name: "Pierre Dubois",
    author_nationality: "Français",
    author_avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80&auto=format&fit=crop&crop=face",
    quote_fr: "SiamLuxe m'a accompagné du premier contact jusqu'à la signature du bail. J'ai acquis mon spa à Sukhumvit en moins de trois semaines avec une rentabilité conforme à ce qui était annoncé.",
    quote_en: "SiamLuxe supported me from first contact to lease signing. I acquired my spa in Sukhumvit in under three weeks, and the yield matches what was announced.",
    quote_ru: "SiamLuxe сопровождал меня от первого контакта до подписания договора. Я приобрёл свой спа в Сукхумвит менее чем за три недели, и доходность соответствует заявленной.",
    rating: 5,
    position: 0,
    visible: true,
    created_at: "2026-02-01T10:00:00Z",
  },
  {
    id: "t2",
    author_name: "Sarah Mitchell",
    author_nationality: "British",
    author_avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&q=80&auto=format&fit=crop&crop=face",
    quote_fr: "L'équipe a sécurisé la due diligence juridique et négocié un prix aligné avec le marché. Mon nail studio à Thonglor atteint son point mort dès le 4ᵉ mois.",
    quote_en: "The team secured legal due diligence and negotiated a market-aligned price. My nail studio in Thonglor broke even by month 4.",
    quote_ru: "Команда обеспечила юридическую проверку и договорилась о справедливой рыночной цене. Мой маникюрный салон в Тонглоре вышел на точку безубыточности к 4-му месяцу.",
    rating: 5,
    position: 1,
    visible: true,
    created_at: "2026-01-15T10:00:00Z",
  },
  {
    id: "t3",
    author_name: "Анатолий Петров",
    author_nationality: "Русский",
    author_avatar_url: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&q=80&auto=format&fit=crop&crop=face",
    quote_fr: "Dossier complet en russe, transparence totale sur les chiffres. Mon centre de massage tourne à plein régime depuis 6 mois et dégage la marge annoncée.",
    quote_en: "Full Russian-language documentation, complete transparency on the numbers. My massage center has been running at full capacity for 6 months and delivers the promised margin.",
    quote_ru: "Полный пакет документов на русском, абсолютная прозрачность цифр. Мой массажный центр работает на полную мощность уже 6 месяцев и приносит обещанную маржу.",
    rating: 5,
    position: 2,
    visible: true,
    created_at: "2025-12-20T10:00:00Z",
  },
  {
    id: "t4",
    author_name: "Marie Laurent",
    author_nationality: "Française",
    author_avatar_url: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&q=80&auto=format&fit=crop&crop=face",
    quote_fr: "La sélection est réellement triée sur le volet : chaque dossier est vérifié, audité et présenté avec un vrai niveau d'analyse. Un vrai partenaire d'investissement.",
    quote_en: "The selection is truly curated: each listing is verified, audited and presented with genuine analysis. A real investment partner.",
    quote_ru: "Подбор действительно тщательный: каждый объект проверен, проанализирован и представлен на серьёзном уровне. Настоящий партнёр по инвестициям.",
    rating: 5,
    position: 3,
    visible: true,
    created_at: "2026-03-01T10:00:00Z",
  },
];

export const GALLERY_IMAGES = [
  "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=600&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1596178060671-7a80dc8059ea?w=600&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=600&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=600&q=80&auto=format&fit=crop",
];
